name: Terraform Apply
on:
  push:
    branches:
    - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    environment: terraform
    steps:
    - uses: actions/checkout@v1
    - name: Verify Terraform version
      run: terraform --version
    - name: Add AWS credentials for Terraform to use
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile sam-user
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile sam-user
      
    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: terraform init -input=false
      
    - name: Terraform validation
      run: terraform validate
    
    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CUSTOM_REFERER_VALUE: ${{ secrets.CUSTOM_REFERER_VALUE }}
      run: terraform apply -auto-approve -input=false -var "custom_header={\"header\"=\"Referer\",\"value\"=\"$CUSTOM_REFERER_VALUE\"}"
